KNOWN_TYPES = {
    # Existing known types
    ".js": "application/javascript",
    ".ts": "application/typescript",
    ".json": "application/json",
    ".md": "text/markdown",
    ".txt": "text/plain",
    ".rst": "text/x-rst",
    ".html": "text/html",
    ".css": "text/css",
    ".csv": "text/csv",
    ".png": "image/png",
    ".svg": "image/svg+xml",
    ".webp": "image/webp",
    ".ttf": "font/ttf",
    ".woff": "font/woff",
    ".woff2": "font/woff2",
    ".xlsm": "application/vnd.ms-excel.sheet.macroEnabled.12",
    ".xlsx": "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
    ".xlsl": "application/octet-stream",
    ".vsixmanifest": "text/xml",
    # Custom project extensions
    ".khml": "application/khml",         # <-- Custom MIME type
    ".sctm": "application/octet-stream",
    ".aura": "application/octet-stream",
    ".berry": "application/octet-stream",
    ".math": "application/octet-stream",
    ".ser": "application/octet-stream",
    ".r": "application/octet-stream",
    ".ml": "application/octet-stream",
    ".mli": "application/octet-stream",
    ".nix": "application/octet-stream",
    ".nex": "application/octet-stream",
}
