name: Dullo CI + Coverage Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test-coverage:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up OCaml
      uses: avsm/setup-ocaml@v1
      with:
        ocaml-version: '5.1.0'

    - name: Install opam dependencies
      run: |
        opam update
        opam install . --deps-only -y

    - name: Build all executables
      run: dune build @all

    - name: Run tests
      run: dune runtest

    - name: Generate coverage report
      run: |
        dune runtest --instrument-with bisect_ppx
        bisect-ppx-report html --coverage-path _build/default
        mv _build/default/_coverage ./coverage

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v6
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./coverage
        publish_branch: gh-pages
