<?php
// $Name: ORG-TEST $, $Id: countryArray.php,v 1.7 2002/10/23 22:59:03 leed Exp $
//---------------------------------------------------------------------
// Copyright (C) 2002 Affero, Inc.

// This file is part of The Affero Project.

// The Affero Project is free software/ you can redistribute it and/or
// modify it under the terms of the Affero General Public License as
// published by Affero, Inc./ either version 1 of the License, or
// (at your option) any later version.

// The Affero Project is distributed in the hope that it will be
// useful,but WITHOUT ANY WARRANTY/ without even the implied warranty
// of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// Affero General Public License for more details.

// You should have received a copy of the Affero General Public
// License in the COPYING file that comes with The Affero Project/ if
// not, write to Affero, Inc., 510 Third Street, Suite 225, San
// Francisco, CA 94107 USA.
//----------------------------------------------------------------------
$COUNTRIES = array (
#    array("code" => "AD", "name" =>"Andorra"),
#    array("code" => "AE", "name" =>"United Arab Emirates"),
#    array("code" => "AF", "name" =>"Afghanistan"),
#    array("code" => "AG", "name" =>"Antigua and Barbuda"),
#    array("code" => "AI", "name" =>"Anguilla"),
#    array("code" => "AL", "name" =>"Albania"),
#    array("code" => "AM", "name" =>"Armenia"),
#    array("code" => "AN", "name" =>"Netherlands Antilles"),
#    array("code" => "AO", "name" =>"Angola"),
#    array("code" => "AQ", "name" =>"Antarctica"),
#    array("code" => "AR", "name" =>"Argentina"),
#    array("code" => "AS", "name" =>"American Samoa"),
#    array("code" => "AT", "name" =>"Austria"),
#    array("code" => "AU", "name" =>"Australia"),
#    array("code" => "AW", "name" =>"Aruba"),
#    array("code" => "AZ", "name" =>"Azerbaijan"),
#    array("code" => "BA", "name" =>"Bosnia and Herzegovina"),
#    array("code" => "BB", "name" =>"Barbados"),
#    array("code" => "BD", "name" =>"Bangladesh"),
#    array("code" => "BE", "name" =>"Belgium"),
#    array("code" => "BF", "name" =>"Burkina Faso"),
#    array("code" => "BG", "name" =>"Bulgaria"),
#    array("code" => "BH", "name" =>"Bahrain"),
#    array("code" => "BI", "name" =>"Burundi"),
#    array("code" => "BJ", "name" =>"Benin"),
#    array("code" => "BM", "name" =>"Bermuda"),
#    array("code" => "BN", "name" =>"Brunei Darussalam"),
#    array("code" => "BO", "name" =>"Bolivia"),
#    array("code" => "BR", "name" =>"Brazil"),
#    array("code" => "BS", "name" =>"Bahamas"),
#    array("code" => "BT", "name" =>"Bhutan"),
#    array("code" => "BV", "name" =>"Bouvet Island"),
#    array("code" => "BW", "name" =>"Botswana"),
#    array("code" => "BY", "name" =>"Belarus"),
#    array("code" => "BZ", "name" =>"Belize"),
#    array("code" => "CA", "name" =>"Canada"),
#    array("code" => "CC", "name" =>"Cocos (Keeling) Islands"),
#    array("code" => "CF", "name" =>"Central African Republic"),
#    array("code" => "CG", "name" =>"Congo"),
#    array("code" => "CH", "name" =>"Switzerland"),
#    array("code" => "CI", "name" =>"Cote D'Ivoire (Ivory Coast)"),
#    array("code" => "CK", "name" =>"Cook Islands"),
#    array("code" => "CL", "name" =>"Chile"),
#    array("code" => "CM", "name" =>"Cameroon"),
#    array("code" => "CN", "name" =>"China"),
#    array("code" => "CO", "name" =>"Colombia"),
#    array("code" => "CR", "name" =>"Costa Rica"),
#    array("code" => "CS", "name" =>"Czechoslovakia (former)"),
#    array("code" => "CU", "name" =>"Cuba"),
#    array("code" => "CV", "name" =>"Cape Verde"),
#    array("code" => "CX", "name" =>"Christmas Island"),
#    array("code" => "CY", "name" =>"Cyprus"),
#    array("code" => "CZ", "name" =>"Czech Republic"),
#    array("code" => "DE", "name" =>"Germany"),
#    array("code" => "DJ", "name" =>"Djibouti"),
#    array("code" => "DK", "name" =>"Denmark"),
#    array("code" => "DM", "name" =>"Dominica"),
#    array("code" => "DO", "name" =>"Dominican Republic"),
#    array("code" => "DZ", "name" =>"Algeria"),
#    array("code" => "EC", "name" =>"Ecuador"),
#    array("code" => "EE", "name" =>"Estonia"),
#    array("code" => "EG", "name" =>"Egypt"),
#    array("code" => "EH", "name" =>"Western Sahara"),
#    array("code" => "ER", "name" =>"Eritrea"),
#    array("code" => "ES", "name" =>"Spain"),
#    array("code" => "ET", "name" =>"Ethiopia"),
#    array("code" => "FI", "name" =>"Finland"),
#    array("code" => "FJ", "name" =>"Fiji"),
#    array("code" => "FK", "name" =>"Falkland Islands (Malvinas)"),
#    array("code" => "FM", "name" =>"Micronesia"),
#    array("code" => "FO", "name" =>"Faroe Islands"),
#    array("code" => "FR", "name" =>"France"),
#    array("code" => "FX", "name" =>"France, Metropolitan"),
#    array("code" => "GA", "name" =>"Gabon"),
#    array("code" => "GB", "name" =>"Great Britain (UK)"),
#    array("code" => "GD", "name" =>"Grenada"),
#    array("code" => "GE", "name" =>"Georgia"),
#    array("code" => "GF", "name" =>"French Guiana"),
#    array("code" => "GH", "name" =>"Ghana"),
#    array("code" => "GI", "name" =>"Gibraltar"),
#    array("code" => "GL", "name" =>"Greenland"),
#    array("code" => "GM", "name" =>"Gambia"),
#    array("code" => "GN", "name" =>"Guinea"),
#    array("code" => "GP", "name" =>"Guadeloupe"),
#    array("code" => "GQ", "name" =>"Equatorial Guinea"),
#    array("code" => "GR", "name" =>"Greece"),
#    array("code" => "GS", "name" =>"S. Georgia and S. Sandwich Isls."),
#    array("code" => "GT", "name" =>"Guatemala"),
#    array("code" => "GU", "name" =>"Guam"),
#    array("code" => "GW", "name" =>"Guinea-Bissau"),
#    array("code" => "GY", "name" =>"Guyana"),
#    array("code" => "HK", "name" =>"Hong Kong"),
#    array("code" => "HM", "name" =>"Heard and McDonald Islands"),
#    array("code" => "HN", "name" =>"Honduras"),
#    array("code" => "HR", "name" =>"Croatia (Hrvatska)"),
#    array("code" => "HT", "name" =>"Haiti"),
#    array("code" => "HU", "name" =>"Hungary"),
#    array("code" => "ID", "name" =>"Indonesia"),
#    array("code" => "IE", "name" =>"Ireland"),
#    array("code" => "IL", "name" =>"Israel"),
#    array("code" => "IN", "name" =>"India"),
#    array("code" => "IO", "name" =>"British Indian Ocean Territory"),
#    array("code" => "IQ", "name" =>"Iraq"),
#    array("code" => "IR", "name" =>"Iran"),
#    array("code" => "IS", "name" =>"Iceland"),
#    array("code" => "IT", "name" =>"Italy"),
#    array("code" => "JM", "name" =>"Jamaica"),
#    array("code" => "JO", "name" =>"Jordan"),
#    array("code" => "JP", "name" =>"Japan"),
#    array("code" => "KE", "name" =>"Kenya"),
#    array("code" => "KG", "name" =>"Kyrgyzstan"),
#    array("code" => "KH", "name" =>"Cambodia"),
#    array("code" => "KI", "name" =>"Kiribati"),
#    array("code" => "KM", "name" =>"Comoros"),
#    array("code" => "KN", "name" =>"Saint Kitts and Nevis"),
#    array("code" => "KP", "name" =>"Korea (North)"),
#    array("code" => "KR", "name" =>"Korea (South)"),
#    array("code" => "KW", "name" =>"Kuwait"),
#    array("code" => "KY", "name" =>"Cayman Islands"),
#    array("code" => "KZ", "name" =>"Kazakhstan"),
#    array("code" => "LA", "name" =>"Laos"),
#    array("code" => "LB", "name" =>"Lebanon"),
#    array("code" => "LC", "name" =>"Saint Lucia"),
#    array("code" => "LI", "name" =>"Liechtenstein"),
#    array("code" => "LK", "name" =>"Sri Lanka"),
#    array("code" => "LR", "name" =>"Liberia"),
#    array("code" => "LS", "name" =>"Lesotho"),
#    array("code" => "LT", "name" =>"Lithuania"),
#    array("code" => "LU", "name" =>"Luxembourg"),
#    array("code" => "LV", "name" =>"Latvia"),
#    array("code" => "LY", "name" =>"Libya"),
#    array("code" => "MA", "name" =>"Morocco"),
#    array("code" => "MC", "name" =>"Monaco"),
#    array("code" => "MD", "name" =>"Moldova"),
#    array("code" => "MG", "name" =>"Madagascar"),
#    array("code" => "MH", "name" =>"Marshall Islands"),
#    array("code" => "MK", "name" =>"Macedonia"),
#    array("code" => "ML", "name" =>"Mali"),
#    array("code" => "MM", "name" =>"Myanmar"),
#    array("code" => "MN", "name" =>"Mongolia"),
#    array("code" => "MO", "name" =>"Macau"),
#    array("code" => "MP", "name" =>"Northern Mariana Islands"),
#    array("code" => "MQ", "name" =>"Martinique"),
#    array("code" => "MR", "name" =>"Mauritania"),
#    array("code" => "MS", "name" =>"Montserrat"),
#    array("code" => "MT", "name" =>"Malta"),
#    array("code" => "MU", "name" =>"Mauritius"),
#    array("code" => "MV", "name" =>"Maldives"),
#    array("code" => "MW", "name" =>"Malawi"),
#    array("code" => "MX", "name" =>"Mexico"),
#    array("code" => "MY", "name" =>"Malaysia"),
#    array("code" => "MZ", "name" =>"Mozambique"),
#    array("code" => "NA", "name" =>"Namibia"),
#    array("code" => "NC", "name" =>"New Caledonia"),
#    array("code" => "NE", "name" =>"Niger"),
#    array("code" => "NF", "name" =>"Norfolk Island"),
#    array("code" => "NG", "name" =>"Nigeria"),
#    array("code" => "NI", "name" =>"Nicaragua"),
#    array("code" => "NL", "name" =>"Netherlands"),
#    array("code" => "NO", "name" =>"Norway"),
#    array("code" => "NP", "name" =>"Nepal"),
#    array("code" => "NR", "name" =>"Nauru"),
#    array("code" => "NT", "name" =>"Neutral Zone"),
#    array("code" => "NU", "name" =>"Niue"),
#    array("code" => "NZ", "name" =>"New Zealand (Aotearoa)"),
#    array("code" => "OM", "name" =>"Oman"),
#    array("code" => "PA", "name" =>"Panama"),
#    array("code" => "PE", "name" =>"Peru"),
#    array("code" => "PF", "name" =>"French Polynesia"),
#    array("code" => "PG", "name" =>"Papua New Guinea"),
#    array("code" => "PH", "name" =>"Philippines"),
#    array("code" => "PK", "name" =>"Pakistan"),
#    array("code" => "PL", "name" =>"Poland"),
#    array("code" => "PM", "name" =>"St. Pierre and Miquelon"),
#    array("code" => "PN", "name" =>"Pitcairn"),
#    array("code" => "PR", "name" =>"Puerto Rico"),
#    array("code" => "PT", "name" =>"Portugal"),
#    array("code" => "PW", "name" =>"Palau"),
#    array("code" => "PY", "name" =>"Paraguay"),
#    array("code" => "QA", "name" =>"Qatar"),
#    array("code" => "RE", "name" =>"Reunion"),
#    array("code" => "RO", "name" =>"Romania"),
#    array("code" => "RU", "name" =>"Russian Federation"),
#    array("code" => "RW", "name" =>"Rwanda"),
#    array("code" => "SA", "name" =>"Saudi Arabia"),
#    array("code" => "Sb", "name" =>"Solomon Islands"),
#    array("code" => "SC", "name" =>"Seychelles"),
#    array("code" => "SD", "name" =>"Sudan"),
#    array("code" => "SE", "name" =>"Sweden"),
#    array("code" => "SG", "name" =>"Singapore"),
#    array("code" => "SH", "name" =>"St. Helena"),
#    array("code" => "SI", "name" =>"Slovenia"),
#    array("code" => "SJ", "name" =>"Svalbard and Jan Mayen Islands"),
#    array("code" => "SK", "name" =>"Slovak Republic"),
#    array("code" => "SL", "name" =>"Sierra Leone"),
#    array("code" => "SM", "name" =>"San Marino"),
#    array("code" => "SN", "name" =>"Senegal"),
#    array("code" => "SO", "name" =>"Somalia"),
#    array("code" => "SR", "name" =>"Suriname"),
#    array("code" => "ST", "name" =>"Sao Tome and Principe"),
#    array("code" => "SU", "name" =>"USSR (former)"),
#    array("code" => "SV", "name" =>"El Salvador"),
#    array("code" => "SY", "name" =>"Syria"),
#    array("code" => "SZ", "name" =>"Swaziland"),
#    array("code" => "TC", "name" =>"Turks and Caicos Islands"),
#    array("code" => "TD", "name" =>"Chad"),
#    array("code" => "TF", "name" =>"French Southern Territories"),
#    array("code" => "TG", "name" =>"Togo"),
#    array("code" => "TH", "name" =>"Thailand"),
#    array("code" => "TJ", "name" =>"Tajikistan"),
#    array("code" => "TK", "name" =>"Tokelau"),
#    array("code" => "TM", "name" =>"Turkmenistan"),
#    array("code" => "TN", "name" =>"Tunisia"),
#    array("code" => "TO", "name" =>"Tonga"),
#    array("code" => "TP", "name" =>"East Timor"),
#    array("code" => "TR", "name" =>"Turkey"),
#    array("code" => "TT", "name" =>"Trinidad and Tobago"),
#    array("code" => "TV", "name" =>"Tuvalu"),
#    array("code" => "TW", "name" =>"Taiwan"),
#    array("code" => "TZ", "name" =>"Tanzania"),
#    array("code" => "UA", "name" =>"Ukraine"),
#    array("code" => "UG", "name" =>"Uganda"),
#    array("code" => "UK", "name" =>"United Kingdom"),
#    array("code" => "UM", "name" =>"US Minor Outlying Islands"),
    array("code" => "US", "name" =>"United States"),
#    array("code" => "UY", "name" =>"Uruguay"),
#    array("code" => "UZ", "name" =>"Uzbekistan"),
#    array("code" => "VA", "name" =>"Vatican City State (Holy See)"),
#    array("code" => "VC", "name" =>"Saint Vincent and the Grenadines"),
#    array("code" => "VE", "name" =>"Venezuela"),
#    array("code" => "VG", "name" =>"Virgin Islands (British)"),
#    array("code" => "VI", "name" =>"Virgin Islands (U.S.)"),
#    array("code" => "VN", "name" =>"Viet Nam"),
#    array("code" => "VU", "name" =>"Vanuatu"),
#    array("code" => "WF", "name" =>"Wallis and Futuna Islands"),
#    array("code" => "WS", "name" =>"Samoa"),
#    array("code" => "YE", "name" =>"Yemen"),
#    array("code" => "YT", "name" =>"Mayotte"),
#    array("code" => "YU", "name" =>"Yugoslavia"),
#    array("code" => "ZA", "name" =>"South Africa"),
#    array("code" => "ZM", "name" =>"Zambia"),
#    array("code" => "ZR", "name" =>"Zaire"),
#    array("code" => "ZW", "name" =>"Zimbabwe"),
    array("code" => "ZZ", "name" =>"Non-US"),

    );
?>
